server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '000822'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
    database: 1