
spring:
  datasource:
    url: jdbc:mysql://193.112.128.94:3306/library?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: library
    password: 'library'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: 193.112.128.94
    port: 6379
    database: 1